language: python
python:
  - 2.7
script: make travis
before_install:
  - echo 'yes' | sudo add-apt-repository ppa:pyside
  - sudo apt-get update
  - sudo apt-get install python-pyside
install:
  - pip install nose
  - pip install Ghost.py==0.1b
