language: python
python:
  - 2.7
script: make travis
before_install:
  - sudo apt-get install python-sip python-qt4
  - python -c 'import sip'
  - python -c 'import PyQt4'
  - python -c 'import PyQt4.QtCore'
install:
  - pip install nose
  - pip install Ghost.py==0.1b
